/**
 * Qurbani Share Factory
 * Creates individual Qurbani share registration records
 */

import { BaseFactory, pickRandom, pickWeighted } from '../base/BaseFactory.js';
import type { Database } from '../../../../src/shared/types/database.types.js';
import { formatDbDate, formatDbDateTime, subMonths, addDays, randomDateBetween } from '../../generators/temporal/date-ranges.js';
import { generateFullName } from '../../generators/names/muslim-names.js';
import { QURBANI_PATTERNS } from '../../config.js';

type QurbaniShare = Database['public']['Tables']['qurbani_shares']['Insert'];

const ANIMAL_TYPES = ['sheep', 'cow', 'camel'] as const;
const DISTRIBUTION_TYPES = ['local_pickup', 'full_charity', 'overseas', 'hybrid'] as const;
const INTENTION_TYPES = ['self', 'family', 'deceased', 'other'] as const;
const STATUSES = ['pending', 'confirmed', 'cancelled', 'completed', 'refunded'] as const;
const PAYMENT_STATUSES = ['pending', 'deposit_paid', 'partial', 'paid', 'refunded'] as const;
const PROCESSING_STATUSES = ['registered', 'slaughtered', 'processed', 'ready_for_pickup', 'distributed', 'completed'] as const;

const PAYMENT_METHODS = ['card', 'cash', 'check', 'bank_transfer'];

export class QurbaniShareFactory extends BaseFactory<QurbaniShare> {
  protected getTableName(): string {
    return 'qurbani_shares';
  }

  protected async getDefaults(): Promise<Partial<QurbaniShare>> {
    // Animal type distribution from config
    const animalType = pickWeighted(QURBANI_PATTERNS.animals) as typeof ANIMAL_TYPES[number];

    // Quantity based on animal type
    const quantity = this.generateQuantity(animalType);

    // Distribution type from config
    const distributionType = pickWeighted(QURBANI_PATTERNS.distribution) as typeof DISTRIBUTION_TYPES[number];

    // Status and payment status
    const status = this.determineStatus();
    const paymentStatus = this.determinePaymentStatus(status);
    const processingStatus = this.determineProcessingStatus(status);

    // Pricing based on animal type (will be set properly when campaign is known)
    const pricing = this.generatePricing(animalType, quantity);

    // Payment info
    const paymentInfo = this.generatePaymentInfo(pricing.totalAmount, paymentStatus);

    // Intention
    const intentionType = pickWeighted({
      self: 50,
      family: 30,
      deceased: 15,
      other: 5,
    }) as typeof INTENTION_TYPES[number];

    // Distribution portions for hybrid
    const distributionPortions = this.generateDistributionPortions(distributionType);

    // Pickup info
    const pickupInfo = this.generatePickupInfo(distributionType);

    return {
      organization_id: '', // Must be set
      campaign_id: '', // Must be set
      share_number: null, // Auto-generated by trigger
      animal_type: animalType,
      quantity,
      member_id: null, // Optionally link to member
      guest_name: Math.random() < 0.3 ? generateFullName() : null, // 30% guest registrations
      guest_email: null,
      guest_phone: null,
      guest_address: null,
      intention_type: intentionType,
      intention_names: this.generateIntentionNames(intentionType),
      intention_notes: null,
      distribution_type: distributionType,
      ...distributionPortions,
      overseas_country: distributionType === 'overseas' || (distributionType === 'hybrid' && distributionPortions.overseas_portion > 0)
        ? pickRandom(['Pakistan', 'Bangladesh', 'Somalia', 'Yemen'])
        : null,
      ...pickupInfo,
      ...pricing,
      ...paymentInfo,
      payment_method: paymentStatus !== 'pending' ? pickRandom(PAYMENT_METHODS) : null,
      payment_reference: paymentStatus === 'paid' ? `PAY-${Math.floor(Math.random() * 100000)}` : null,
      payment_date: paymentStatus === 'paid' ? formatDbDate(subMonths(new Date(), 1)) : null,
      status,
      processing_status: processingStatus,
      slaughtered_at: processingStatus !== 'registered' && processingStatus !== 'slaughtered'
        ? formatDbDateTime(subMonths(new Date(), 0.5))
        : null,
      distributed_at: processingStatus === 'distributed' || processingStatus === 'completed'
        ? formatDbDateTime(subMonths(new Date(), 0.3))
        : null,
      cancelled_at: status === 'cancelled'
        ? formatDbDateTime(subMonths(new Date(), 2))
        : null,
      cancellation_reason: status === 'cancelled'
        ? pickRandom(['Changed mind', 'Financial reasons', 'Personal reasons'])
        : null,
      refund_amount: status === 'cancelled' || status === 'refunded'
        ? paymentInfo.amount_paid * 0.8
        : null,
      notes: null,
      internal_notes: null,
    };
  }

  private generateQuantity(animalType: string): number {
    if (animalType === 'sheep') {
      return 1; // Sheep is always 1 full share
    }
    // Cow/camel can be 1-7 shares
    return pickWeighted({
      1: 50, // Most common
      2: 20,
      3: 10,
      7: 20, // Full animal
    }) as number;
  }

  private determineStatus(): typeof STATUSES[number] {
    return pickWeighted({
      pending: 10,
      confirmed: 40,
      cancelled: 5,
      completed: 43,
      refunded: 2,
    }) as typeof STATUSES[number];
  }

  private determinePaymentStatus(status: string): typeof PAYMENT_STATUSES[number] {
    if (status === 'pending') {
      return pickWeighted({ pending: 40, deposit_paid: 60 }) as typeof PAYMENT_STATUSES[number];
    }
    if (status === 'confirmed') {
      return pickWeighted({ deposit_paid: 20, partial: 30, paid: 50 }) as typeof PAYMENT_STATUSES[number];
    }
    if (status === 'completed') {
      return 'paid';
    }
    if (status === 'cancelled') {
      return pickWeighted({ pending: 20, deposit_paid: 40, refunded: 40 }) as typeof PAYMENT_STATUSES[number];
    }
    return 'pending';
  }

  private determineProcessingStatus(status: string): typeof PROCESSING_STATUSES[number] {
    if (status === 'pending' || status === 'cancelled') {
      return 'registered';
    }
    if (status === 'confirmed') {
      return pickWeighted({
        registered: 30,
        slaughtered: 20,
        processed: 20,
        ready_for_pickup: 30,
      }) as typeof PROCESSING_STATUSES[number];
    }
    if (status === 'completed') {
      return pickWeighted({
        distributed: 40,
        completed: 60,
      }) as typeof PROCESSING_STATUSES[number];
    }
    return 'registered';
  }

  private generatePricing(animalType: string, quantity: number): {
    unit_price: number;
    total_amount: number;
    currency: string;
  } {
    const prices: Record<string, number> = {
      sheep: 250,
      cow: 400, // Per share
      camel: 550, // Per share
    };

    const unitPrice = prices[animalType] || 250;
    const totalAmount = unitPrice * quantity;

    return {
      unit_price: unitPrice,
      total_amount: totalAmount,
      currency: 'USD',
    };
  }

  private generatePaymentInfo(totalAmount: number, paymentStatus: string): {
    amount_paid: number;
  } {
    const deposit = 50;

    switch (paymentStatus) {
      case 'pending':
        return { amount_paid: 0 };
      case 'deposit_paid':
        return { amount_paid: deposit };
      case 'partial':
        return { amount_paid: deposit + Math.floor(Math.random() * (totalAmount - deposit)) };
      case 'paid':
        return { amount_paid: totalAmount };
      case 'refunded':
        return { amount_paid: 0 };
      default:
        return { amount_paid: 0 };
    }
  }

  private generateIntentionNames(intentionType: string): string[] {
    switch (intentionType) {
      case 'self':
        return [generateFullName()];
      case 'family':
        return [
          generateFullName(),
          generateFullName(),
          generateFullName(),
        ];
      case 'deceased':
        return [generateFullName() + ' (deceased)'];
      default:
        return [generateFullName()];
    }
  }

  private generateDistributionPortions(distributionType: string): {
    pickup_portion: number;
    charity_portion: number;
    overseas_portion: number;
  } {
    if (distributionType === 'local_pickup') {
      return { pickup_portion: 1, charity_portion: 0, overseas_portion: 0 };
    }
    if (distributionType === 'full_charity') {
      return { pickup_portion: 0, charity_portion: 1, overseas_portion: 0 };
    }
    if (distributionType === 'overseas') {
      return { pickup_portion: 0, charity_portion: 0, overseas_portion: 1 };
    }
    // Hybrid - common split is 1/3 each
    const portions = pickRandom([
      { pickup_portion: 0.33, charity_portion: 0.33, overseas_portion: 0.34 },
      { pickup_portion: 0.5, charity_portion: 0.5, overseas_portion: 0 },
      { pickup_portion: 0.5, charity_portion: 0, overseas_portion: 0.5 },
      { pickup_portion: 0.33, charity_portion: 0.67, overseas_portion: 0 },
    ]);
    return portions;
  }

  private generatePickupInfo(distributionType: string): {
    pickup_location: string | null;
    pickup_date: string | null;
    pickup_time: string | null;
    pickup_notes: string | null;
  } {
    if (distributionType === 'full_charity' || distributionType === 'overseas') {
      return {
        pickup_location: null,
        pickup_date: null,
        pickup_time: null,
        pickup_notes: null,
      };
    }

    return {
      pickup_location: pickRandom(['Main Mosque', 'Community Center']),
      pickup_date: null, // Would be set based on campaign dates
      pickup_time: pickRandom(['8:00 AM - 10:00 AM', '10:00 AM - 12:00 PM', '12:00 PM - 2:00 PM', '2:00 PM - 4:00 PM']),
      pickup_notes: Math.random() < 0.2 ? 'Please bring cooler' : null,
    };
  }

  withOrganization(organizationId: string): this {
    return this.with({ organization_id: organizationId });
  }

  withCampaign(campaignId: string): this {
    return this.with({ campaign_id: campaignId });
  }

  withMember(memberId: string): this {
    return this.with({ member_id: memberId, guest_name: null });
  }

  asGuest(name: string, email?: string, phone?: string): this {
    return this.with({
      member_id: null,
      guest_name: name,
      guest_email: email || null,
      guest_phone: phone || null,
    });
  }

  asSheep(): this {
    return this.with({
      animal_type: 'sheep',
      quantity: 1,
      unit_price: 250,
      total_amount: 250,
    });
  }

  asCowShare(shares: number = 1): this {
    const unitPrice = 400;
    return this.with({
      animal_type: 'cow',
      quantity: Math.min(shares, 7),
      unit_price: unitPrice,
      total_amount: unitPrice * Math.min(shares, 7),
    });
  }

  asLocalPickup(): this {
    return this.with({
      distribution_type: 'local_pickup',
      pickup_portion: 1,
      charity_portion: 0,
      overseas_portion: 0,
    });
  }

  asFullCharity(): this {
    return this.with({
      distribution_type: 'full_charity',
      pickup_portion: 0,
      charity_portion: 1,
      overseas_portion: 0,
    });
  }

  asOverseas(country: string): this {
    return this.with({
      distribution_type: 'overseas',
      pickup_portion: 0,
      charity_portion: 0,
      overseas_portion: 1,
      overseas_country: country,
    });
  }

  asCompleted(): this {
    return this.with({
      status: 'completed',
      payment_status: 'paid',
      processing_status: 'completed',
    });
  }

  asPending(): this {
    return this.with({
      status: 'pending',
      payment_status: 'deposit_paid',
      processing_status: 'registered',
    });
  }
}
