/**
 * Service Case Factory
 * Creates social service case records with KPI tracking
 */

import { BaseFactory, pickRandom, pickWeighted } from '../base/BaseFactory.js';
import type { Database } from '../../../../src/shared/types/database.types.js';
import { formatDbDate, formatDbDateTime, subMonths, randomDateBetween, addDays } from '../../generators/temporal/date-ranges.js';
import { CASE_PATTERNS } from '../../config.js';

type ServiceCase = Database['public']['Tables']['service_cases']['Insert'];

const STATUSES = ['open', 'in_progress', 'pending', 'resolved', 'closed', 'cancelled'] as const;
const PRIORITIES = ['low', 'medium', 'high', 'urgent'] as const;

const CASE_TYPES = [
  'Financial Assistance',
  'Counseling',
  'New Muslim Support',
  'Family Mediation',
  'Legal Assistance',
  'Housing Assistance',
  'Food Assistance',
  'Medical Assistance',
  'Job Search Support',
  'Immigration Support',
  'Funeral Assistance',
  'General Support',
];

const CASE_TITLES = {
  'Financial Assistance': [
    'Rent assistance needed',
    'Utility bill support request',
    'Medical bill assistance',
    'Emergency financial help',
    'School fee support',
  ],
  'Counseling': [
    'Family counseling request',
    'Marriage counseling',
    'Youth counseling needed',
    'Grief counseling',
    'Pre-marriage counseling',
  ],
  'New Muslim Support': [
    'New Muslim - Shahada certificate',
    'New Muslim guidance needed',
    'Convert support request',
    'New Muslim integration help',
  ],
  'Family Mediation': [
    'Family dispute mediation',
    'Divorce mediation request',
    'Parent-child conflict',
    'Inheritance dispute',
  ],
  'Legal Assistance': [
    'Legal consultation needed',
    'Immigration legal help',
    'Tenant rights assistance',
    'Contract review needed',
  ],
};

const OUTCOMES = ['Approved', 'Partially Approved', 'Denied', 'Referred', 'Resolved', 'Self-Resolved', 'Ongoing'];

interface NoteThread {
  id: string;
  author_name: string;
  content: string;
  created_at: string;
  is_internal: boolean;
}

export class ServiceCaseFactory extends BaseFactory<ServiceCase> {
  protected getTableName(): string {
    return 'service_cases';
  }

  protected async getDefaults(): Promise<Partial<ServiceCase>> {
    // Case type distribution from config
    const caseType = pickWeighted(CASE_PATTERNS.types) as string;

    // Priority distribution
    const priority = pickWeighted(CASE_PATTERNS.priorities) as typeof PRIORITIES[number];

    // Status based on realistic case lifecycle
    const status = this.determineStatus();

    // Created date 1-18 months ago
    const monthsAgo = Math.floor(Math.random() * 17) + 1;
    const createdAt = subMonths(new Date(), monthsAgo);

    // Resolution info based on status
    const resolutionInfo = this.generateResolutionInfo(status, createdAt);

    // Financial info for financial assistance cases
    const financialInfo = this.generateFinancialInfo(caseType);

    // Generate notes thread
    const notesThread = this.generateNotesThread(status, createdAt);

    // Title based on case type
    const titles = CASE_TITLES[caseType as keyof typeof CASE_TITLES] || [`${caseType} request`];
    const title = pickRandom(titles);

    return {
      organization_id: '', // Must be set
      case_number: null, // Auto-generated by trigger
      member_id: null, // Optionally link to member
      case_type: caseType.toLowerCase().replace(/\s+/g, '_'),
      category: null,
      title,
      description: this.generateDescription(caseType),
      status,
      priority,
      ...financialInfo,
      assistance_date: null,
      due_date: status === 'open' || status === 'in_progress'
        ? formatDbDate(addDays(new Date(), Math.floor(Math.random() * 14) + 7))
        : null,
      ...resolutionInfo,
      assigned_to: null, // Would need auth.users reference
      assigned_at: status !== 'open' ? formatDbDateTime(addDays(createdAt, 1)) : null,
      notes_thread: notesThread,
      is_confidential: Math.random() < 0.7, // 70% confidential
      requires_followup: status === 'resolved' && Math.random() < 0.3,
      followup_date: null,
      created_at: formatDbDateTime(createdAt),
    };
  }

  private determineStatus(): typeof STATUSES[number] {
    return pickWeighted({
      open: 15,
      in_progress: 25,
      pending: 10,
      resolved: 35,
      closed: 12,
      cancelled: 3,
    }) as typeof STATUSES[number];
  }

  private generateResolutionInfo(status: string, createdAt: Date): {
    resolved_date: string | null;
    resolution_notes: string | null;
    outcome: string | null;
    closed_at: string | null;
  } {
    if (status === 'resolved' || status === 'closed') {
      // Resolution time from config patterns
      const resolutionDays = pickWeighted({
        fast: CASE_PATTERNS.resolutionTime.fast.weight,
        normal: CASE_PATTERNS.resolutionTime.normal.weight,
        slow: CASE_PATTERNS.resolutionTime.slow.weight,
        very_slow: CASE_PATTERNS.resolutionTime.very_slow.weight,
      });

      let days: number;
      switch (resolutionDays) {
        case 'fast':
          days = Math.floor(Math.random() * 7) + 1;
          break;
        case 'normal':
          days = Math.floor(Math.random() * 23) + 7;
          break;
        case 'slow':
          days = Math.floor(Math.random() * 60) + 30;
          break;
        default:
          days = Math.floor(Math.random() * 90) + 90;
      }

      const resolvedDate = addDays(createdAt, days);
      const outcome = pickRandom(OUTCOMES);

      return {
        resolved_date: formatDbDate(resolvedDate),
        resolution_notes: this.generateResolutionNotes(outcome),
        outcome,
        closed_at: formatDbDateTime(resolvedDate),
      };
    }

    return {
      resolved_date: null,
      resolution_notes: null,
      outcome: null,
      closed_at: null,
    };
  }

  private generateFinancialInfo(caseType: string): {
    requested_amount: number | null;
    approved_amount: number | null;
    disbursed_amount: number;
    fund_id: string | null;
  } {
    const financialTypes = ['Financial Assistance', 'Housing Assistance', 'Medical Assistance', 'Funeral Assistance'];

    if (!financialTypes.includes(caseType)) {
      return {
        requested_amount: null,
        approved_amount: null,
        disbursed_amount: 0,
        fund_id: null,
      };
    }

    // Requested amount varies by type
    const maxAmounts: Record<string, number> = {
      'Financial Assistance': 2000,
      'Housing Assistance': 3000,
      'Medical Assistance': 5000,
      'Funeral Assistance': 4000,
    };

    const maxAmount = maxAmounts[caseType] || 1500;
    const requestedAmount = Math.floor(Math.random() * maxAmount) + 200;

    // Approval rate ~70%
    const approved = Math.random() < 0.7;
    const approvedAmount = approved
      ? Math.min(requestedAmount, Math.floor(requestedAmount * (0.5 + Math.random() * 0.5)))
      : null;

    // Disbursement rate for approved ~90%
    const disbursed = approvedAmount && Math.random() < 0.9;
    const disbursedAmount = disbursed ? approvedAmount : 0;

    return {
      requested_amount: requestedAmount,
      approved_amount: approvedAmount,
      disbursed_amount: disbursedAmount,
      fund_id: null, // Would need actual fund ID
    };
  }

  private generateDescription(caseType: string): string {
    const descriptions: Record<string, string[]> = {
      'Financial Assistance': [
        'Family is facing temporary financial hardship due to job loss. Need assistance with rent payment.',
        'Single parent struggling to pay utility bills. Has been a community member for 5 years.',
        'Student needs help with tuition fees for the upcoming semester.',
      ],
      'Counseling': [
        'Couple seeking marriage counseling to work through communication issues.',
        'Family requesting youth counseling for teenager going through difficulties.',
        'Individual seeking grief counseling after loss of family member.',
      ],
      'New Muslim Support': [
        'Recently took Shahada and looking for guidance on practicing Islam.',
        'Convert seeking community support and mentorship.',
        'New Muslim requesting help with learning prayers and basics of faith.',
      ],
    };

    const typeDescriptions = descriptions[caseType] || [
      `Request for ${caseType.toLowerCase()} from community member.`,
    ];

    return pickRandom(typeDescriptions);
  }

  private generateResolutionNotes(outcome: string): string {
    const notes: Record<string, string[]> = {
      'Approved': [
        'Request approved after review. Funds disbursed to applicant.',
        'Case approved. Support provided as requested.',
      ],
      'Partially Approved': [
        'Partial assistance approved based on available funds.',
        'Request partially fulfilled due to budget constraints.',
      ],
      'Denied': [
        'Unable to approve request at this time. Applicant did not meet criteria.',
        'Request denied. Referred to alternative resources.',
      ],
      'Referred': [
        'Case referred to external organization for specialized support.',
        'Referred to partner agency for additional assistance.',
      ],
      'Resolved': [
        'Case resolved successfully. Client satisfied with outcome.',
        'Issue resolved through counseling sessions.',
      ],
    };

    const outcomeNotes = notes[outcome] || ['Case closed.'];
    return pickRandom(outcomeNotes);
  }

  private generateNotesThread(status: string, createdAt: Date): NoteThread[] {
    const notes: NoteThread[] = [];
    const staffNames = ['Imam Abdullah', 'Sister Fatima', 'Brother Ahmad', 'Sister Maryam', 'Brother Yusuf'];

    // Initial intake note
    notes.push({
      id: crypto.randomUUID(),
      author_name: pickRandom(staffNames),
      content: 'Initial intake completed. Case assigned for review.',
      created_at: formatDbDateTime(addDays(createdAt, 0)),
      is_internal: true,
    });

    if (status !== 'open') {
      // Assignment note
      notes.push({
        id: crypto.randomUUID(),
        author_name: pickRandom(staffNames),
        content: 'Case assigned. Will contact client within 48 hours.',
        created_at: formatDbDateTime(addDays(createdAt, 1)),
        is_internal: true,
      });
    }

    if (['in_progress', 'pending', 'resolved', 'closed'].includes(status)) {
      // Progress note
      notes.push({
        id: crypto.randomUUID(),
        author_name: pickRandom(staffNames),
        content: 'Contacted client. Gathering required documentation.',
        created_at: formatDbDateTime(addDays(createdAt, 3)),
        is_internal: false,
      });
    }

    if (['resolved', 'closed'].includes(status)) {
      // Resolution note
      notes.push({
        id: crypto.randomUUID(),
        author_name: pickRandom(staffNames),
        content: 'Case resolved. Follow-up scheduled if needed.',
        created_at: formatDbDateTime(addDays(createdAt, 14)),
        is_internal: true,
      });
    }

    return notes;
  }

  withOrganization(organizationId: string): this {
    return this.with({ organization_id: organizationId });
  }

  withMember(memberId: string): this {
    return this.with({ member_id: memberId });
  }

  withFund(fundId: string): this {
    return this.with({ fund_id: fundId });
  }

  withCaseType(caseType: string): this {
    return this.with({ case_type: caseType });
  }

  withPriority(priority: typeof PRIORITIES[number]): this {
    return this.with({ priority });
  }

  asOpen(): this {
    return this.with({ status: 'open' });
  }

  asInProgress(): this {
    return this.with({ status: 'in_progress' });
  }

  asResolved(): this {
    return this.with({ status: 'resolved' });
  }

  asClosed(): this {
    return this.with({ status: 'closed' });
  }

  asUrgent(): this {
    return this.with({ priority: 'urgent' });
  }

  asFinancialAssistance(): this {
    return this.with({
      case_type: 'financial_assistance',
      title: 'Financial assistance request',
    });
  }

  asCounseling(): this {
    return this.with({
      case_type: 'counseling',
      title: 'Counseling request',
    });
  }

  asNewMuslimSupport(): this {
    return this.with({
      case_type: 'new_muslim_support',
      title: 'New Muslim support request',
    });
  }
}
