/**
 * Trip Registration Factory
 * Creates pilgrim registration records for trips
 */

import { BaseFactory, pickRandom, pickWeighted } from '../base/BaseFactory.js';
import type { Database } from '../../../../src/shared/types/database.types.js';
import { formatDbDate, formatDbDateTime, subMonths, addDays, randomDateBetween } from '../../generators/temporal/date-ranges.js';
import { UMRAH_PATTERNS } from '../../config.js';

type TripRegistration = Database['public']['Tables']['trip_registrations']['Insert'];

const STATUSES = ['pending', 'confirmed', 'waitlisted', 'cancelled', 'completed', 'no_show'] as const;
const PAYMENT_STATUSES = ['pending', 'deposit_paid', 'partial', 'paid', 'refunded'] as const;
const VISA_STATUSES = ['not_started', 'documents_submitted', 'processing', 'approved', 'rejected', 'issued'] as const;
const ROOM_TYPES = ['single', 'double', 'triple', 'quad', 'family'] as const;

const EMERGENCY_RELATIONS = ['Spouse', 'Parent', 'Sibling', 'Child', 'Friend', 'Other Family'];

export class TripRegistrationFactory extends BaseFactory<TripRegistration> {
  protected getTableName(): string {
    return 'trip_registrations';
  }

  protected async getDefaults(): Promise<Partial<TripRegistration>> {
    const status = pickWeighted({
      pending: 15,
      confirmed: 50,
      waitlisted: 5,
      cancelled: 10,
      completed: 18,
      no_show: 2,
    }) as typeof STATUSES[number];

    // Payment status correlates with registration status
    const paymentStatus = this.determinePaymentStatus(status);

    // Visa status for confirmed/completed registrations
    const visaStatus = this.determineVisaStatus(status);

    // Room type distribution from config
    const roomType = pickWeighted(UMRAH_PATTERNS.roomTypes) as typeof ROOM_TYPES[number];

    // Registration date 1-6 months ago
    const monthsAgo = Math.floor(Math.random() * 6) + 1;
    const registrationDate = subMonths(new Date(), monthsAgo);

    // Pricing
    const totalAmount = this.generateTotalAmount(roomType);
    const paymentInfo = this.generatePaymentInfo(totalAmount, paymentStatus);

    return {
      organization_id: '', // Must be set
      trip_id: '', // Must be set
      member_id: '', // Must be set
      registration_date: formatDbDate(registrationDate),
      registration_number: null, // Auto-generated by trigger
      status,
      payment_status: paymentStatus,
      total_amount: totalAmount,
      deposit_paid: paymentInfo.depositPaid,
      amount_paid: paymentInfo.amountPaid,
      currency: 'USD',
      payment_deadline: formatDbDate(addDays(registrationDate, 60)),
      room_type: roomType,
      room_sharing_with: [],
      passport_number: this.generatePassportNumber(),
      passport_expiry: formatDbDate(addDays(new Date(), Math.floor(Math.random() * 730) + 365)), // 1-3 years
      passport_country: pickRandom(['United States', 'Canada', 'United Kingdom']),
      visa_status: visaStatus,
      visa_number: visaStatus === 'issued' ? this.generateVisaNumber() : null,
      visa_issue_date: visaStatus === 'issued' ? formatDbDate(subMonths(new Date(), 1)) : null,
      visa_expiry_date: visaStatus === 'issued' ? formatDbDate(addDays(new Date(), 90)) : null,
      visa_notes: null,
      medical_conditions: Math.random() < 0.1 ? pickRandom(['Diabetes', 'High blood pressure', 'Asthma', 'Knee problems']) : null,
      dietary_requirements: Math.random() < 0.15 ? pickRandom(['Vegetarian', 'Halal only', 'No nuts', 'Diabetic diet']) : null,
      emergency_contact_name: this.generateEmergencyContactName(),
      emergency_contact_phone: this.generatePhoneNumber(),
      emergency_contact_relation: pickRandom(EMERGENCY_RELATIONS),
      flight_details: {},
      special_requests: Math.random() < 0.2 ? this.generateSpecialRequest() : null,
      accessibility_needs: Math.random() < 0.05 ? 'Wheelchair assistance required' : null,
      notes: null,
      internal_notes: null,
      cancelled_at: status === 'cancelled' ? formatDbDateTime(addDays(registrationDate, Math.floor(Math.random() * 30) + 7)) : null,
      cancellation_reason: status === 'cancelled' ? pickRandom(['Personal reasons', 'Health issues', 'Family emergency', 'Financial reasons']) : null,
      refund_amount: status === 'cancelled' ? paymentInfo.amountPaid * 0.7 : null, // 70% refund
      refund_date: status === 'cancelled' ? formatDbDate(addDays(registrationDate, 45)) : null,
    };
  }

  private determinePaymentStatus(status: string): typeof PAYMENT_STATUSES[number] {
    if (status === 'pending' || status === 'waitlisted') {
      return pickWeighted({ pending: 60, deposit_paid: 40 }) as typeof PAYMENT_STATUSES[number];
    }
    if (status === 'confirmed') {
      return pickWeighted({ deposit_paid: 20, partial: 30, paid: 50 }) as typeof PAYMENT_STATUSES[number];
    }
    if (status === 'completed') {
      return 'paid';
    }
    if (status === 'cancelled') {
      return pickWeighted({ pending: 20, deposit_paid: 30, partial: 20, refunded: 30 }) as typeof PAYMENT_STATUSES[number];
    }
    return 'pending';
  }

  private determineVisaStatus(status: string): typeof VISA_STATUSES[number] {
    if (status === 'pending' || status === 'waitlisted') {
      return 'not_started';
    }
    if (status === 'confirmed') {
      return pickWeighted({
        not_started: 10,
        documents_submitted: 20,
        processing: 30,
        approved: 25,
        issued: 15,
      }) as typeof VISA_STATUSES[number];
    }
    if (status === 'completed') {
      return 'issued';
    }
    return 'not_started';
  }

  private generateTotalAmount(roomType: string): number {
    const basePrices: Record<string, number> = {
      single: 4500,
      double: 3500,
      triple: 3000,
      quad: 2800,
      family: 3200,
    };

    const basePrice = basePrices[roomType] || 3500;
    // Add some variation
    const variation = Math.floor(Math.random() * 500) - 250;
    return basePrice + variation;
  }

  private generatePaymentInfo(totalAmount: number, paymentStatus: string): {
    depositPaid: number;
    amountPaid: number;
  } {
    const depositAmount = Math.round(totalAmount * 0.25);

    switch (paymentStatus) {
      case 'pending':
        return { depositPaid: 0, amountPaid: 0 };
      case 'deposit_paid':
        return { depositPaid: depositAmount, amountPaid: depositAmount };
      case 'partial':
        const partial = depositAmount + Math.floor(Math.random() * (totalAmount - depositAmount));
        return { depositPaid: depositAmount, amountPaid: partial };
      case 'paid':
        return { depositPaid: depositAmount, amountPaid: totalAmount };
      case 'refunded':
        return { depositPaid: depositAmount, amountPaid: depositAmount };
      default:
        return { depositPaid: 0, amountPaid: 0 };
    }
  }

  private generatePassportNumber(): string {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let result = '';
    for (let i = 0; i < 9; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  }

  private generateVisaNumber(): string {
    return `V${Math.floor(Math.random() * 900000000) + 100000000}`;
  }

  private generateEmergencyContactName(): string {
    const firstNames = ['Ahmed', 'Fatima', 'Omar', 'Aisha', 'Yusuf', 'Maryam', 'Ibrahim', 'Khadijah'];
    const lastNames = ['Khan', 'Ali', 'Hassan', 'Ahmed', 'Rahman', 'Malik', 'Hussain'];
    return `${pickRandom(firstNames)} ${pickRandom(lastNames)}`;
  }

  private generatePhoneNumber(): string {
    const areaCode = Math.floor(Math.random() * 900) + 100;
    const prefix = Math.floor(Math.random() * 900) + 100;
    const line = Math.floor(Math.random() * 9000) + 1000;
    return `(${areaCode}) ${prefix}-${line}`;
  }

  private generateSpecialRequest(): string {
    const requests = [
      'Room near elevator please',
      'Lower floor room preferred',
      'Need room close to sisters in group',
      'Wheelchair accessible room needed',
      'Request for extra pillows',
      'Need early check-in if possible',
    ];
    return pickRandom(requests);
  }

  withOrganization(organizationId: string): this {
    return this.with({ organization_id: organizationId });
  }

  withTrip(tripId: string): this {
    return this.with({ trip_id: tripId });
  }

  withMember(memberId: string): this {
    return this.with({ member_id: memberId });
  }

  asConfirmed(): this {
    return this.with({
      status: 'confirmed',
      payment_status: 'paid',
    });
  }

  asPending(): this {
    return this.with({
      status: 'pending',
      payment_status: 'deposit_paid',
    });
  }

  asCompleted(): this {
    return this.with({
      status: 'completed',
      payment_status: 'paid',
      visa_status: 'issued',
    });
  }

  asCancelled(): this {
    return this.with({ status: 'cancelled' });
  }

  withRoomType(roomType: typeof ROOM_TYPES[number]): this {
    return this.with({ room_type: roomType });
  }

  asDoubleRoom(): this {
    return this.withRoomType('double');
  }

  asQuadRoom(): this {
    return this.withRoomType('quad');
  }
}
