// This file will be auto-generated by Supabase CLI
// For now, we define a basic structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          country_id: string | null
          address: string | null
          city: string | null
          state: string | null
          zip_code: string | null
          timezone: string | null
          contact_email: string | null
          contact_phone: string | null
          website: string | null
          logo_url: string | null
          primary_color: string | null
          settings: Json
          payment_config: Json
          setup_progress: Json
          is_active: boolean
          created_at: string
          updated_at: string
          created_by: string | null
          updated_by: string | null
        }
        Insert: {
          id?: string
          name: string
          slug: string
          country_id?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip_code?: string | null
          timezone?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          website?: string | null
          logo_url?: string | null
          primary_color?: string | null
          settings?: Json
          payment_config?: Json
          setup_progress?: Json
          is_active?: boolean
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          country_id?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip_code?: string | null
          timezone?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          website?: string | null
          logo_url?: string | null
          primary_color?: string | null
          settings?: Json
          payment_config?: Json
          setup_progress?: Json
          is_active?: boolean
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
        }
      }
      members: {
        Row: {
          id: string
          organization_id: string
          household_id: string | null
          user_id: string | null
          first_name: string
          last_name: string
          email: string | null
          phone: string | null
          date_of_birth: string | null
          date_of_birth_hijri: string | null
          gender: string | null
          address: string | null
          city: string | null
          state: string | null
          zip_code: string | null
          membership_type: string
          membership_status: string
          joined_date: string
          photo_url: string | null
          notes: string | null
          custom_fields: Json
          created_at: string
          updated_at: string
          created_by: string | null
          updated_by: string | null
        }
        Insert: {
          id?: string
          organization_id: string
          household_id?: string | null
          user_id?: string | null
          first_name: string
          last_name: string
          email?: string | null
          phone?: string | null
          date_of_birth?: string | null
          date_of_birth_hijri?: string | null
          gender?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip_code?: string | null
          membership_type?: string
          membership_status?: string
          joined_date?: string
          photo_url?: string | null
          notes?: string | null
          custom_fields?: Json
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
        }
        Update: {
          id?: string
          organization_id?: string
          household_id?: string | null
          user_id?: string | null
          first_name?: string
          last_name?: string
          email?: string | null
          phone?: string | null
          date_of_birth?: string | null
          date_of_birth_hijri?: string | null
          gender?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip_code?: string | null
          membership_type?: string
          membership_status?: string
          joined_date?: string
          photo_url?: string | null
          notes?: string | null
          custom_fields?: Json
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
        }
      }
      // Add more tables as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
